#H2 settings
spring:
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:6434/db_eventstore
    driverClassName: org.postgresql.Driver
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        jdbc:
          lob:
            non_contextual_creation: true

server:
  servlet:
    context-path: /demo
  port: 8080

